name: Bug report
description: Report a reproducible problem
title: "[Bug] "
labels: ["bug"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Build / CI
        - CLI
        - USB / libusb
        - PIT
        - Flashing
        - Crypto
        - LZ4
        - Packaging
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Odin4 version
      placeholder: "4.x.y-commit"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device model
      placeholder: "SM-XXXX"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
    validations:
      required: true
