name: Feature request
description: Suggest an improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - New feature
        - Improvement
        - Refactor
        - Documentation
        - CI / Release
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
