name: Question
description: Ask about usage or development
title: "[Question] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      render: shell
    validations:
      required: false
