name: OpenSSF Scorecard

on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # toda semana

jobs:
  scorecard:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read
      id-token: write

    steps:
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif